import json
import logging
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger('AuditLogic')

SUBSCRIPTION_PATTERNS = {
    'netflix.com': 'Netflix',
    'spotify.com': 'Spotify',
    'adobe.com': 'Adobe Creative Cloud',
    'notion.so': 'Notion',
    'slack.com': 'Slack',
    'github.com': 'GitHub Copilot',
}

def analyze_transaction(transaction):
    for pattern, name in SUBSCRIPTION_PATTERNS.items():
        if pattern in transaction['description'].lower():
            return {
                'type': 'subscription',
                'name': name,
                'amount': transaction.get('amount', 0),
                'date': transaction.get('date', datetime.now().isoformat())
            }
    return None

def run_weekly_audit(vault_path: Path):
    """
    Simulates a weekly audit by reading Business_Goals, analyzing transactions (if any),
    and generating a CEO Briefing draft in Pending_Approval.
    """
    logger.info("Starting Weekly Business & Accounting Audit...")
    goals_file = vault_path / "Business_Goals.md"
    pending_approval = vault_path / "Pending_Approval"
    briefings_dir = vault_path / "Briefings"
    briefings_dir.mkdir(exist_ok=True)
    
    # Normally this would read actual accounting/bank info, but for phase 1 we'll mock the analysis.
    # We will generate a draft briefing.
    
    today_str = datetime.now().strftime("%Y-%m-%d")
    briefing_filename = f"APPROVAL_REQUIRED_Briefing_{today_str}.md"
    
    goals_content = goals_file.read_text('utf-8') if goals_file.exists() else "No goals set."
    
    # Create the draft briefing
    briefing_content = f"""---
type: ceo_briefing
action: approve_report
generated: {datetime.now().isoformat()}
period: Past Week
status: pending
---

# Monday Morning CEO Briefing

## Executive Summary
This is an automatically generated audit of the past week's business activities, cross-referenced with your `Business_Goals.md`.

## Goals Context
```text
{goals_content[:300]}...
```

## Proactive Suggestions

### Cost Optimization
- **Notion**: No team activity in 45 days. Cost: $15/month.
  - [ACTION] Cancel subscription? (AI will execute if approved)

### Upcoming Deadlines
- Verify Project milestone deliveries for this week.

---
*Generated by AI Employee (Gold Tier)*
"""
    
    dest_path = pending_approval / briefing_filename
    dest_path.write_text(briefing_content, encoding='utf-8')
    logger.info(f"CEO Briefing drafted at {dest_path}")

if __name__ == "__main__":
    run_weekly_audit(Path("D:/Urooj/Hackthon 0/AI_Employee_Vault"))
